version: '3.9'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://espadas:espadas123@db:5432/rinha

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: espadas
      POSTGRES_PASSWORD: espadas123
    ports:
      - "15432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U espadas -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5